config/routes.rb
Rails.application.routes.draw do
  root to: 'pages#show'
  resource :pages, only: %i[show]

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def show
    @current_page = params[:id].to_i.positive? ? params[:id].to_i : 1
    @count = params[:count].present? ? params[:count].to_i : 1
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/home/page7.html.haml
.center
  .ball-list
    .ball.blue
    .ball.blue
    .ball.blue
    .ball.blue
    .ball.blue
  .ball-list
    .ball.yellow
    .ball.yellow
    .ball.yellow
    .ball.yellow
    .ball.yellow
  %a.ball.red{ href: (@count < 5 ? page7_path(count: @count + 1) : page8_path) }

app/views/home/page8.html.haml
.center
  .ball-list
    .ball.blue
    .ball.blue
    .ball.blue
    .ball.blue
    .ball.blue
  .ball-list
    .ball.yellow
    .ball.yellow
    .ball.yellow
    .ball.yellow
    .ball.yellow
  .ball-list
    .ball.red
    .ball.red
    .ball.red
    .ball.red
    .ball.red

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title Press Here
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_pack_tag 'application', 'data-turbolinks-track': 'reload'
    = turbo_include_tags
  %body
    = yield

app/views/pages/_page1.html.haml
.center
  = link_to '', pages_path(id: 2), class: 'ball yellow'

app/views/pages/_page2.html.haml
.center
  = link_to '', pages_path(id: 3), class: 'ball yellow'
  = link_to '', pages_path(id: 3), class: 'ball yellow'

app/views/pages/_page3.html.haml
.center
  = link_to '', pages_path(id: 4), class: 'ball yellow rub'
  .ball.yellow
  .ball.yellow

app/views/pages/_page4.html.haml
.center
  .ball.blue
  .ball.yellow
  = link_to '', pages_path(id: 5), class: 'ball yellow rub'

app/views/pages/_page5.html.haml
.center
  .ball.blue
  - next_url = count < 5 ? pages_path(id: 5, count: count + 1) : pages_path(id: 6)
  = link_to '', next_url, class: 'ball yellow'
  .ball.red

app/views/pages/_page6.html.haml
.center
  - next_url = count < 5 ? pages_path(id: 6, count: count + 1) : pages_path(id: 7)
  = link_to '', next_url, class: 'ball blue'
  .ball-list
    .ball.yellow
    .ball.yellow
    .ball.yellow
    .ball.yellow
    .ball.yellow
  .ball.red

app/views/pages/_page7.html.haml
.center
  .ball-list
    .ball.blue
    .ball.blue
    .ball.blue
    .ball.blue
    .ball.blue
  .ball-list
    .ball.yellow
    .ball.yellow
    .ball.yellow
    .ball.yellow
    .ball.yellow
  - next_url = count < 5 ? pages_path(id: 7, count: count + 1) : pages_path(id: 8)
  = link_to '', next_url, class: 'ball red'

app/views/pages/_page8.html.haml
.center
  .ball-list
    .ball.blue
    .ball.blue
    .ball.blue
    .ball.blue
    .ball.blue
  .ball-list
    .ball.yellow
    .ball.yellow
    .ball.yellow
    .ball.yellow
    .ball.yellow
  .ball-list
    .ball.red
    .ball.red
    .ball.red
    .ball.red
    .ball.red

app/views/pages/show.html.haml
= turbo_frame_tag 'page' do
  = render partial: "page#{@current_page}", locals: { count: @count }